travis:
  secure:
    BINSTAR_TOKEN: iFWg5hpssN0KLUek9YZnhWtfCUO500ygHPTyILcmKkVCgrnCUzXFFJYoDSWOSNWVDOJOI9utkNxpVhntgFJPKDb9H67+A4KeIwE1wrPYlILuqMTR7A9XErlA91WbQSbjFSGOjzfSZYe5SG9hPVAc61PVCVaYKnsu1t/4Srh6amehYtWGG1JirgJYu8btzq6NLbIkKs2uNKAiSsSWeTrVqd4zYn5GRHaPYhznvSdkJbrgLuh2u1G7OJT0KaNpb+0Y0GceqoDj1c/SVsdH20HHUoZ+/DfM3cM4x3Cn9zofh23INHGKVJdzRii0unUajhdJtfvI9JJ4oOfLZ8QMc8xiDvStSluf2Pqeqnt/7UrYg3Wbdy9ozERtFrp6OmWGlorEl0BEO9SLTBt3PJkUltZBqxfeJqkgdtFx0U9AiFDm/Tm2nNuPhpoqLC+WWxxmi73hGyfTIKB2QNRlyNuNrVjAmfnljWl35e5UaL4HedL2snzbY5Wugo/WaFTdip3TZ9kSJflg1KWiXFTeiVYMrZxqnbK/Wg6ooEMbelcD1U9FGckmVIwD+5Cmf9aTpBWauRZ89szH3NUVjHFlMfLbgmwVIoY+nmlKs7qY4bDWYGbEXKVReO4sJdfoS9V6WoSkOVTaFsd4dutilPGaNVZqSCOTJ+6Cokx88XhuUSBiL9AgeQs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
