travis:
  secure:
    BINSTAR_TOKEN: ek90+q2v2EV8wyTwkRrwanZzUADY6/8EERiyIXBvmX1bbGSDNdStKTAXxnOm69+mic/fi4rYXTRC9rdrlAbfquz8Np7voQGa8JSmxn5aFqeUiv0PjOrIHlRycmV1AndnZademLpv3AJyq+gdQiohvKMPZreIKW8S5Y13k0O4kuMZfd9FUGnx642lYPyzvnDwVYM0EPv9H7YEzfPa36pYlUXgXCMKfOwmAYRwt1U9MxbaTyIo54cdcIDBuOLhQOGhalNdlhhU/+XqS8Q5q1ZAyBTVhsjT2AVtrQivThpiy5LTrAPu3xExW90qxJg3b206HNWHP4hHR2zFtx9y5njlLIdfdenavzP+fKKKBTHucd+HzIn/8C6JYfo+8Qe0bLaL9KPwLunfcE5cTou2GOBRa9SqEqSxLhpScRKU33XDvO8+5npB1DWo4ug4zvn0rKX23E/NrtXJKfn9zM3uPEwzMdmRzL7X0fgBxlmxdUPYqn6nm5IS4on98/KxgxG8ivExktPwZtQJ5oo+hzJj1y6m3cBW1usBBNFUsxRYY6IFmSlC1FGxV+rwO8mrxKi+GiUEkG8fkrMF14NodtO+mpXqdU0iXUF+I7rrEQeWXMTOVTduDF3eyrCH0cBbIQtfLPFJ1HrysqI2BnwZ6WjHuUbtHszOCv9Y+PUMO0KBIIIGlTE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
